name: Release
env:
  BIN: kwcpu

on:
  push:
    tags:
      - "[0-9]+\\.[0-9]+\\.[0-9]+" # Push events to matching semver tags

jobs:
  Upload-Zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      # Zip the src directory contents and append the rmskin footer
      - run: |
          7z a "${{ env.BIN }}.zip" ./src/* -r
          python zip2rmskin.py "${{ env.BIN }}.zip"

      - uses: XAMPPRocky/create-release@v1.0.2
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          # Draft should **always** be false. GitHub doesn't provide a way to
          # get draft releases from its API, so there's no point using it.
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.BIN }}.zip
          asset_name: ${{ env.BIN }}-${{ steps.get_version.outputs.VERSION }}.rmskin
          asset_content_type: application/zip
